#  Assignment 5

This assignment covers material on matrices, norms, condition numbers and eigensystems. The assignment is due by 5pm on Friday the 17th of April.

The breakdown of the marks is as follows:

Question 0 - [1 mark]  
Question 1 - [7 marks]  
Questino 2 - [6 marks]  
Question 3 - [7 marks]  
Question 4 - [9 marks]  

# Question 0

You should have saved this notebook to your ACM20030-Assignments folder. Now:
- commit the notebook to your local repository
- push the changes to the GitHub

In [1]:
import numpy as np
from numpy import linalg as la
np.set_printoptions(linewidth=200)  # This stops line wrapping of larger matrices

# Question 1 - practice manipulating arrays

This questions asks you write a few functions for manipulating arrays of data

## Q1 a

Write a function that checks if a given $n\times n$ matrix is symmetric. Use only loops and `.shape` function from numpy (do not use any other special numpy functions).

In [2]:
def SymmetryCheck(M):
    N = np.shape(M)[0]
    #print(N) for debugging
    for i in range(N):
        for j in range(N):
            if M[i][j] == M[j][i]:
                continue
            else:
                return "false"
    return "true"

Test your function on the two matrices below

In [3]:
A = np.random.rand(5,5)
SymMatrix = (A + A.T)/2

In [4]:
print("Matrix A is symmetric:",SymmetryCheck(A))
print("Matrix SymMatrix is symmetric:",SymmetryCheck(SymMatrix))

Matrix A is symmetric: false
Matrix SymMatrix is symmetric: true


## Q1 b

Write a function to transpose a general $n\times n$ matrix. Do this by writing loops and not using any special functions like `np.transpose()`, `A.T`, or any functions from any other library.

In [5]:
def MatrixTranspose(M):
    N = np.shape(M)[0]
    B = np.zeros(np.shape(M))
    for i in range(N):
        for j in range(N):
            B[i][j] = M[j][i]
    return B

Check your code by transposing the below random matrix and checking that $A^T \neq A$ and $(A^T)^T - A = 0$

In [6]:
A = np.random.rand(6,6)
print("A:",A)

# Transposing the matrix A
B = MatrixTranspose(A)
print("A transposed:",B)

# Checking if A is symmetric
print("The matrix A is symmetric:",SymmetryCheck(A))
print("Therefore the matrix A is not equal to its transpose.")

# Transposing the transpose of the matrix A and checking that it equals A
C = MatrixTranspose(B)
print(C - A)
print("As expected")

A: [[0.44879926 0.33095921 0.22595027 0.78445654 0.10422976 0.71775217]
 [0.92246124 0.59020179 0.37057843 0.75951268 0.44931295 0.22685043]
 [0.75243854 0.14546183 0.11928302 0.15682113 0.51262346 0.93382475]
 [0.6532511  0.24962423 0.04796771 0.28961585 0.32334051 0.7655543 ]
 [0.0305599  0.95814489 0.35491982 0.5053979  0.87328427 0.41653742]
 [0.41692498 0.08693376 0.68599709 0.93240081 0.34575596 0.80543461]]
A transposed: [[0.44879926 0.92246124 0.75243854 0.6532511  0.0305599  0.41692498]
 [0.33095921 0.59020179 0.14546183 0.24962423 0.95814489 0.08693376]
 [0.22595027 0.37057843 0.11928302 0.04796771 0.35491982 0.68599709]
 [0.78445654 0.75951268 0.15682113 0.28961585 0.5053979  0.93240081]
 [0.10422976 0.44931295 0.51262346 0.32334051 0.87328427 0.34575596]
 [0.71775217 0.22685043 0.93382475 0.7655543  0.41653742 0.80543461]]
The matrix A is symmetric: false
Therefore the matrix A is not equal to its transpose.
[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0

## Q1c

Write a function that finds the maximum entry in a matrix (where the matrix does not need to be square). Do this by writing loops and not using any special functions like `np.max` or any functions from any other library.

In [7]:
def maxEntry(M):
    X,Y = np.shape(M)
    # Starting comparisons with the first entry in the matrix in case the matrix contains large negative numbers exclusively
    runningmax = M[0][0]
    #print(runningmax) for debugging
    for i in range(X):
        for j in range(Y):
            # if the entry being compared is greater than the previously largest found value, set it as the largest found value
            if M[i][j] > runningmax:
                runningmax = M[i][j]
    return runningmax

Check your result by comparing to `np.max(A)` for the below random matrix

In [8]:
A = np.random.rand(4,5)
print("A:",A)
print("The max value in the matrix A using the written function:",maxEntry(A))
print("The max value in the matrix A using np.max():",np.max(A))

A: [[0.62853668 0.80321012 0.11310259 0.01535611 0.46947107]
 [0.74365972 0.79296431 0.01751109 0.0977682  0.31444005]
 [0.31701993 0.59756776 0.56061271 0.27173668 0.37217616]
 [0.262758   0.26563474 0.43109616 0.96992313 0.75393922]]
The max value in the matrix A using the written function: 0.9699231269232466
The max value in the matrix A using np.max(): 0.9699231269232466


# Question 2:  matrix norms

In the lectures we focused on the $L^2$-norm. We also briefly mentioned the $L^1$ and $L^\infty$ norm. Let's look at calculating those as well for a general $m\times n$ matrix.

# Q2a

The $L^1$ norm is given by

$$ \lVert A \rVert_1 = \max_j \sum^m_{i=1} |a_{ij}| $$

i.e., it is the max of the sums of the absolute values of each column. Write a function that computes the $L^1$-norm using only loops. The function should use no special numpy functions except `np.abs()`.

In [9]:
def L1(A):
    X,Y = np.shape(A)
    # Defining the initial max value to be 0 since every sum of the absolute values of a column must be greater than or equal to 0
    columnmax = 0
    for j in range(Y):
        columntotal = 0
        for i in range(X):
            columntotal += np.abs(A[i][j])
            #print("cm",columnmax,"ct",columntotal,"i",i,"j",j) for debugging
        if columntotal > columnmax:
            columnmax = columntotal
    return columnmax

Check your result against NumPy's `la.norm(A,1)` function for the following random matrix

In [10]:
A = np.random.rand(3,4)
print("L\N{SUPERSCRIPT ONE} norm using written function =",L1(A))
print("L\N{SUPERSCRIPT ONE} norm using la.norm(A,1) =",la.norm(A,1))

L¹ norm using written function = 2.2820816619469393
L¹ norm using la.norm(A,1) = 2.2820816619469393


## Q2b

The $L^\infty$ norm is given by 

$$\lVert A \rVert_\infty = \max_i \sum_{j=1}^n |a_{ij}|$$

i.e., it is the max of the sums of the absolute values of each row. Write a function that computes the $L^\infty$-norm using only loops and no special numpy functions.

In [11]:
def Linf(A):
    X,Y = np.shape(A)
    # Again, defining the initial max value to be 0 since every sum of the absolute values of a row must be greater than or equal to 0
    rowmax = 0
    for i in range(X):
        rowtotal = 0
        for j in range(Y):
            rowtotal += np.abs(A[i][j])
            #print("cm",columnmax,"ct",columntotal,"i",i,"j",j) for debugging
        if rowtotal > rowmax:
            rowmax = rowtotal
    return rowmax

Check your result against NumPy's `la.norm(A,np.inf)` function for the following random matrix

In [12]:
A = np.random.rand(3,4)
print("L^inf norm using written function =",Linf(A))
print("L^inf norm using la.norm(A,np.inf) =",la.norm(A,np.inf))

L^inf norm using written function = 2.3139212290015867
L^inf norm using la.norm(A,np.inf) = 2.3139212290015867


# Question 3: ill-conditions systems of equations

In this question you can use any of NumPy's functions.

## Q3a

Which of the following three matrices, $A1, A2, A3$, are ill-conditioned. State the reason for your conclusion.

In [13]:
A1 = np.array([[0.988746460106, 0.351486109477, 0.024911477532, 0.384039749683],
       [0.282104657306, 0.239884151775, 0.36170151991 , 0.903082266861],
       [0.59333290915 , 0.637178863968, 0.241229214635, 0.685595037901],
       [0.013591747828, 0.917926970364, 0.458689093885, 0.157821121254]])

A2 = np.array([[ 2.852416473483e-01,  3.803483118694e-01,  2.697704226632e-01,  6.810611849029e-01],
       [ 6.622827828376e-01,  6.447943415836e-01,  4.387842058829e-01,  1.530575702376e+00],
       [ 3.672130860703e-01,  8.309522079704e-01,  9.975487474007e-01,  5.678296337101e-01],
       [ 4.036490000599e-01,  6.865978225967e-06,  8.788095913773e-01, -7.150472427928e-02]])

A3 = np.array([[0.131923621844, 0.245316154195, 0.732362341613, 0.957047891764],
       [0.91290446184 , 0.512312007959, 0.391938831444, 0.092509684772],
       [0.648708523652, 0.608576675797, 0.576773587276, 0.065385122929],
       [0.502955480393, 0.084082960221, 0.659487390444, 0.662958739412]])

In [14]:
print("Condition number for A1:",la.cond(A1,2))
print("Condition number for A2:",la.cond(A2,2))
print("Condition number for A3:",la.cond(A3,2))

print("Given the large condition number of the matrix A2 (how sensitive the matrix is to changes),\n we can conclude that A2 is ill-conditioned.")

Condition number for A1: 21.552466488381846
Condition number for A2: 13334936994.070848
Condition number for A3: 15.12244969941062
Given the large condition number of the matrix A2 (how sensitive the matrix is to changes),
 we can conclude that A2 is ill-conditioned.


# Q3b

With $b = [1,2,3,4]$ and $\delta b = [0.1,0,0,0]$ for $A2$ and $A3$ calculate the percentage change in $x$ due to a small change in $b$, i.e., calculate 

$$100\times\frac{\lVert \delta x_i\rVert_2}{\lVert x_i \rVert_2}\quad\text{and}\quad 100\times\frac{\lVert \delta b\rVert_2}{\lVert b \rVert_2}$$

where $(x_i+\delta x_i)  = A_i^{-1}(b+\delta b)$ and $i\in\{2,3\}$.

In [15]:
#Definind functions for dx, x
def dx(A): 
    return la.inv(A)@([1.1,2,3,4])-la.inv(A)@([1,2,3,4])

def x(A):
    return la.inv(A)@([1,2,3,4])

# The percentage change in x for A2:

a2 = 100*(la.norm(dx(A2),2)/la.norm(x(A2),2))

# The percentage change in x for A3:

a3 = 100*(la.norm(dx(A3),2)/la.norm(x(A3),2))

# For both A2 and A3, the value of the percentage change in b is the same:

b = np.array([1,2,3,4])
deltab = np.array([0.1,0,0,0])

print("Percentage change in A2 = ", a2, "%")
print("Percentage change in A3 = ", a3, "%")
print("Percentage change in b (for both A2 and A3) = ", 100*(la.norm(deltab,2)/la.norm(b,2)), "%")

Percentage change in A2 =  512.6206098890646 %
Percentage change in A3 =  2.173811243421917 %
Percentage change in b (for both A2 and A3) =  1.8257418583505536 %


Which system of equations is more sensitive to small changes in $b$? How could you have guessed this from the answer to the Q3a?

In [16]:
# A2 is more sensitive to small changes in b. This confirms what we assumed from the condition number of A2 in Q3a.

# Question 4: eigensystems

In this question we look at finding eigenvalues and eigenvectors

## Q4a

You may use any of NumPy's functions for this sub-question.

Find the eigenvalues and eigenvectors for the below matrix. Print out the eigenvalues sorted by descending value and explicitly show that eigenvalues/eigenvector pairs satisfy $Ax = \lambda x$.

In [17]:
A = np.array([[1,4,5],[4,5,4],[6,7,9]])

In [18]:
# Calculating the eigenvalues and corresponding eigenvectors using linalg from numpy
eigen = la.eig(A)
#print(eigen)

evalues = eigen[0]
evectors = eigen[1]

# Calculating an index that would sort the arrays by descending eigenvalue (and sort their respective eigenvectors into this new order)
sortorder = np.argsort(evalues)[::-1]

# Sorting both arrays
s_values = evalues[sortorder]
s_vectors = evectors[:,sortorder]

print("Eigenvalues sorted by descending value:\n", s_values)
print("Corresponding eigenvectors in column form:\n",s_vectors)

print("Explicitly showing that the eigenvalues/eigenvector pairs satisfy Ax\N{LATIN SUBSCRIPT SMALL LETTER I} = \N{GREEK SMALL LETTER LAMDA}x:")

# Pair 1

print("Ax\N{SUBSCRIPT ONE} =", np.dot(A,np.transpose(s_vectors[:,0])))
print("\N{GREEK SMALL LETTER LAMDA}x\N{SUBSCRIPT ONE} =",s_values[0]*s_vectors[:,0])

# Pair 2

print("Ax\N{SUBSCRIPT TWO} =", np.dot(A,np.transpose(s_vectors[:,1])))
print("\N{GREEK SMALL LETTER LAMDA}x\N{SUBSCRIPT TWO} =",s_values[1]*s_vectors[:,1])


# Pair 3

print("Ax\N{SUBSCRIPT THREE} =", np.dot(A,np.transpose(s_vectors[:,2])))
print("\N{GREEK SMALL LETTER LAMDA}x\N{SUBSCRIPT THREE} =",s_values[2]*s_vectors[:,2])


Eigenvalues sorted by descending value:
 [15.78569318  1.26595327 -2.05164645]
Corresponding eigenvectors in column form:
 [[-0.39252008  0.09818766 -0.89589878]
 [-0.44424151 -0.77454142  0.36255198]
 [-0.80534308  0.6248558   0.25675168]]
Explicitly showing that the eigenvalues/eigenvector pairs satisfy Axᵢ = λx:
Ax₁ = [ -6.1962015   -7.01266016 -12.71289871]
λx₁ = [ -6.1962015   -7.01266016 -12.71289871]
Ax₂ = [ 0.12430099 -0.98053324  0.79103825]
λx₂ = [ 0.12430099 -0.98053324  0.79103825]
Ax₃ = [ 1.83806756 -0.74382849 -0.52676368]
λx₃ = [ 1.83806756 -0.74382849 -0.52676368]


# Q4b

Without using NumPy's `la.eig()` (or similar functions), find the 4 eigenvalues and eigenvectors of the following matrix. Hint: Use the power method for the max eigenvalue (given below in `MaxEigenvalue`), the power method applied to the inverse for the smallest eigenvalue, and apply Hotelling's deflation twice to find the second and third eigenvalues/eigenvectors.

In [27]:
A = np.array([[1.935052353404, 0.887037260957, 1.534235483277, 1.370691224125],
       [0.887037260957, 0.81275989158 , 0.610238622918, 0.999150521052],
       [1.534235483277, 0.610238622918, 1.562260333538, 1.007843062517],
       [1.370691224125, 0.999150521052, 1.007843062517, 1.813258814483]])

In [28]:
def MaxEigenvalue(A, err):
    (m,n) = A.shape
    if(m != n):
        print("Matrix must be square")
        return
    x = np.random.rand(m)
    
    lam = 0.1
    lamprev = 1
    while np.abs(1-lam/lamprev) > err:
        p = np.dot(A,x)
        lamprev = lam
        lam = np.max(p)
        x = p/lam
        
    x = x/la.norm(x)
    return (lam,x)

In [29]:
# Using the power method for the max eigenvalue/eigenvector
maxEigen = MaxEigenvalue(A,1e-14)
l1 = maxEigen[0]
e1 = maxEigen[1]

# Using Hotelling's deflation twice to find the second and third eigenvalues/eigenvectors
B = A -l1*np.outer(e1,e1)

lsecond  = MaxEigenvalue(B, 1e-12)
l2 = lsecond[0]
e2 = lsecond[1]

C = B -l2*np.outer(e2,e2)

lthird = MaxEigenvalue(C, 1e-12)
l3 = lthird[0]
e3 = lthird[1]


# Using the power method applied to the inverse for the smallest eigenvalue/eigenvector
pl4 = 1/(MaxEigenvalue(la.inv(A),1e-14)[0])
pe4 = MaxEigenvalue(la.inv(A),1e-14)[1]
minEigen = (pl4,pe4)

print("Eigenvalues with their corresponding eigenvectors:\n",maxEigen,"\n",lsecond,"\n",lthird,"\n",minEigen)

Eigenvalues with their corresponding eigenvectors:
 (4.91480442349976, array([0.59947641, 0.33318806, 0.49528112, 0.53320761])) 
 (0.8505815318667769, array([ 0.30724064, -0.3894447 ,  0.58292464, -0.64353313])) 
 (0.21512836395732082, array([-0.3811686 , -0.67389895,  0.34000478,  0.53382343])) 
 (0.1428170736816672, array([-0.63319959,  0.53214542,  0.54707607, -0.12879172]))


Check your answers against Numpy's results from `la.eig(A)`

In [30]:
la.eig(A)
# Which equals the output from the cell above (with the eigenvectors in column form)

(array([4.91480442, 0.85058153, 0.14281707, 0.21512836]),
 array([[ 0.59947641,  0.30724064, -0.63319959, -0.3811686 ],
        [ 0.33318806, -0.3894447 ,  0.53214542, -0.67389895],
        [ 0.49528112,  0.58292464,  0.54707607,  0.34000478],
        [ 0.53320761, -0.64353313, -0.12879172,  0.53382343]]))